name: CI/CD Pipeline for Dev Environment

on:
  workflow_call:

jobs:
  deploy-to-ecs-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run tests
        run: echo "Running tests for dev environment"

      - name: Deploy to dev
        run: echo "Deploying to dev environment"

      - name: Notify
        run: echo "Notifying the team about the deployment to dev environment"
