name: CI/CD Pipeline for dev Environment

on:
  workflow_call:

jobs:
  clone-repo-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          repository: "nvlannasik/github-action-manifest"
          path: "dockerfile"

      - name: Display Files
        run: cat dockerfile/${{ env.DOCKERFILE_NAME }}

      - name: Create a ENV_EXAMPLE
        run: echo "example_env=dev" > env-file

      - name: Upload ENV_EXAMPLE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: env-file

  build-image:
    runs-on: ubuntu-latest
    needs: clone-repo-manifest
    steps:
      - name: Download ENV_EXAMPLE artifact
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Read ENV_EXAMPLE
        run: |
          cat env-file
          export $(cat env-file | xargs)
          echo "ENV_EXAMPLE is $example_env"

      - name: print ENV_EXAMPLE
        run: echo $ENV_EXAMPLE

      - name: show files
        run: ls -l
