name: CI/CD Pipeline for Dev Environment

on:
  workflow_call:

jobs:
  clone-repo-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Display Files
        run: echo ls -l

      - name: Display environment variables
        run: printenv

      - name: Create a ENV_EXAMPLE
        run: export ENV_EXAMPLE=dev

      - name: Display ENV_EXAMPLE
        run: echo $ENV_EXAMPLE

  build-image:
    runs-on: ubuntu-latest
    needs: clone-repo-manifest
    steps:
      - name: printenv
        run: printenv

      - name: print ENV_EXAMPLE
        run: echo $ENV_EXAMPLE

      - name: show files
        run: ls -l
