name: CI/CD Pipeline for Dev Environment

on:
  workflow_call:

jobs:
  testing-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests for dev environment"

      - name: Deploy to dev
        run: echo "Deploying to dev environment"
