name: CI/CD Pipeline for staging Environment

on:
  workflow_call:
    inputs:
      dockerfile_name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  prepare-properites-repo-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository manifest
        run: |
          mkdir -p $HOME/properties-repo-manifest
          echo https://github.com/nvlannasik/github-action-manifest.git
          echo ${{ secrets.GH_TOKEN }}
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/nvlannasik/github-action-manifest.git $HOME/properties-repo-manifest/github-action-manifest
          cd $HOME/properties-repo-manifest/github-action-manifest
          ls -la

      - name: Upload properties-repo as artifact
        uses: actions/upload-artifact@v3
        with:
          name: properties-repo
          path: $HOME/properties-repo-manifest/github-action-manifest

  build-image:
    runs-on: ubuntu-latest
    needs: prepare-properites-repo-manifest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download external repository as artifact
        uses: actions/download-artifact@v3
        with:
          name: properties-repo

      - name: Check downloaded properties-repo-manifest
        run: |
          ls -la $HOME/properties-repo
          ls -la $HOME/properties-repo/github-action-manifest

      - name: Display Files
        run: cat $HOME/properties-repo/github-action-manifest/dockerfile/${{ inputs.dockerfile_name }}
