name: CI/CD Pipeline for staging Environment

on:
  workflow_call:
    inputs:
      dockerfile_name:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true

jobs:
  prepare-properties-repo-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository manifest
        run: |
          mkdir -p ${{ github.workspace }}/properties-repo-manifest
          echo "Cloning into: ${{ github.workspace }}/properties-repo-manifest/github-action-manifest"
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/nvlannasik/github-action-manifest.git ${{ github.workspace }}/properties-repo-manifest/github-action-manifest
          cd ${{ github.workspace }}/properties-repo-manifest/github-action-manifest
          ls -la

      - name: Upload properties-repo as artifact
        uses: actions/upload-artifact@v4
        with:
          name: properties-repo
          path: ${{ github.workspace }}/properties-repo-manifest/github-action-manifest

  build-image:
    runs-on: ubuntu-latest
    needs: prepare-properties-repo-manifest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: check files in the repository
        run: |
          ls -la

      - name: Download external repository as artifact
        uses: actions/download-artifact@v4
        with:
          name: properties-repo
          path: ../downloaded-properties

      - name: check files in the repository
        run: |
          ls -la

      - name: Check downloaded properties-repo-manifest
        run: |
          ls -la ../downloaded-properties

      - name: check files in the repository
        run: |
          ls -la

      - name: Display Files
        run: |
          cat ../downloaded-properties/dockerfile/${{ inputs.dockerfile_name }}
