name: CI/CD Pipeline for Staging Environment

on:
  workflow_call:
  workflow_dispatch:
    # inputs:
    #   environment:
    #     description: 'Environment to deploy to'
    #     required: true
    #     default: 'staging'
    #     validation:
    #       pattern: '^(staging)$'

jobs:
  deploy-to-ecs-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: echo "Running tests for Staging environment"

      - name: Deploy to dev
        run: echo "Deploying to Staging environment"

      - name: Notify
        run: echo "Notifying the team about the deployment to Staging environment"
