name: CI/CD Pipeline for staging Environment

on:
  workflow_call:

jobs:
  clone-repo-manifest:
    runs-on: ubuntu-latest
    outputs:
      example_env: ${{ steps.set_env.outputs.example_env }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4

      - name: Display Files
        run: echo ls -l

      - name: Create a ENV_EXAMPLE
        id: set_env
        run: echo "example_env=dev" >> $GITHUB_ENV

      - name: Upload ENV_EXAMPLE as artifact
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: $GITHUB_ENV

  build-image:
    runs-on: ubuntu-latest
    needs: clone-repo-manifest
    steps:
      - name: Download ENV_EXAMPLE artifact
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Read ENV_EXAMPLE
        run: |
          cat env-file
          export $(cat env-file | xargs)
          echo "ENV_EXAMPLE is $example_env"

      - name: print ENV_EXAMPLE
        run: echo $ENV_EXAMPLE

      - name: show files
        run: ls -l
